# Generated by Django 5.0.4 on 2026-03-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='节点编号')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('system_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='系统名称')),
                ('machine_node', models.CharField(blank=True, max_length=100, null=True, verbose_name='机器节点名')),
                ('finger', models.CharField(blank=True, max_length=100, null=True, verbose_name='机器指纹')),
                ('host', models.CharField(blank=True, max_length=100, null=True, verbose_name='内网主机地址')),
                ('admin_port', models.IntegerField(default=9001, verbose_name='管理端口')),
                ('version', models.FloatField(default=0, verbose_name='版本号')),
                ('flag', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目标识')),
                ('is_auth', models.IntegerField(default=0, verbose_name='是否授权')),
                ('is_multi_process', models.IntegerField(default=0, verbose_name='是否多进程')),
                ('max_count', models.IntegerField(default=0, verbose_name='最大布控数')),
                ('auth_msg', models.CharField(blank=True, max_length=200, null=True, verbose_name='授权消息')),
                ('ws_connected', models.BooleanField(default=False, verbose_name='WebSocket连接状态')),
                ('ws_channel', models.CharField(blank=True, max_length=200, null=True, verbose_name='WebSocket通道')),
                ('ws_connect_time', models.DateTimeField(blank=True, null=True, verbose_name='连接时间')),
                ('ws_last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='客户端IP')),
                ('register_info', models.TextField(blank=True, null=True, verbose_name='注册信息')),
                ('project_start_timestamp', models.IntegerField(default=0, verbose_name='软件启动时间戳')),
                ('os_boot_timestamp', models.IntegerField(default=0, verbose_name='系统启动时间戳')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'cp_node',
                'verbose_name_plural': 'cp_node',
                'db_table': 'cp_node',
            },
        ),
        migrations.CreateModel(
            name='NodeHeartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_code', models.CharField(max_length=50, verbose_name='节点编号')),
                ('heartbeat_time', models.DateTimeField(verbose_name='心跳时间')),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='客户端IP')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'cp_node_heart',
                'verbose_name_plural': 'cp_node_heart',
                'db_table': 'cp_node_heart',
                'ordering': ['-heartbeat_time'],
                'indexes': [models.Index(fields=['node_code'], name='cp_node_hea_node_co_42afb5_idx'), models.Index(fields=['heartbeat_time'], name='cp_node_hea_heartbe_cb3290_idx')],
            },
        ),
    ]
