# Generated by Django 5.0.4 on 2026-03-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodemodel',
            name='ws_last_heartbeat',
        ),
    ]
