# Generated by Django 5.0.4 on 2026-03-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_nodemodel_ws_last_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAlarmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='sort')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('draw_type', models.IntegerField(verbose_name='合成报警视频画框类型')),
                ('flag', models.CharField(max_length=50, verbose_name='合成报警视频标记')),
                ('node_code', models.CharField(max_length=100, verbose_name='node_code')),
                ('control_code', models.CharField(max_length=50, verbose_name='布控编号')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('video_path', models.TextField(verbose_name='视频存储路径')),
                ('video_count', models.IntegerField(verbose_name='视频总数量')),
                ('image_path', models.TextField(verbose_name='主图存储路径')),
                ('image_count', models.IntegerField(verbose_name='图片总数量')),
                ('other_image_count', models.IntegerField(verbose_name='其他图片数量')),
                ('level', models.IntegerField(verbose_name='报警级别')),
                ('state', models.IntegerField(verbose_name='状态')),
                ('is_check', models.IntegerField(verbose_name='是否检测')),
                ('review_remark', models.CharField(max_length=200, verbose_name='审核备注')),
                ('stream_app', models.CharField(max_length=50, verbose_name='视频流应用')),
                ('stream_name', models.CharField(max_length=100, verbose_name='视频流名称')),
                ('stream_code', models.CharField(max_length=50, verbose_name='视频流编号')),
                ('flow_mode', models.IntegerField(verbose_name='业务算法模式')),
                ('flow_code', models.CharField(max_length=50, verbose_name='业务算法编号')),
                ('flow_name', models.CharField(max_length=100, verbose_name='业务算法名称')),
                ('main_plate_color', models.IntegerField(default=0, verbose_name='关键帧车牌颜色')),
                ('main_plate_type', models.IntegerField(default=0, verbose_name='关键帧车牌类型')),
                ('main_plate_no', models.CharField(default='', max_length=100, verbose_name='关键帧车牌号')),
                ('main_track_max_code', models.CharField(default='', max_length=50, verbose_name='特征最大匹配编号')),
                ('main_track_max_custom_code', models.CharField(default='', max_length=50, verbose_name='特征最大匹配自定义编号')),
                ('main_track_max_similary', models.IntegerField(default=0, verbose_name='特征最大相似度')),
                ('expand1', models.CharField(default='', max_length=200, verbose_name='expand1')),
                ('expand2', models.CharField(default='', max_length=200, verbose_name='expand2')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('create_timestamp', models.IntegerField(verbose_name='create_timestamp')),
                ('last_update_time', models.DateTimeField(verbose_name='last_update_time')),
            ],
            options={
                'verbose_name': 'cp_platform_alarm',
                'verbose_name_plural': 'cp_platform_alarm',
                'db_table': 'cp_platform_alarm',
            },
        ),
        migrations.CreateModel(
            name='PlatformAlgorithmFlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('flow_code', models.CharField(max_length=50, verbose_name='flow_code')),
                ('flow_name', models.CharField(max_length=100, verbose_name='flow_name')),
                ('node_codes', models.TextField(verbose_name='节点编号列表')),
                ('state', models.IntegerField(verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('last_update_time', models.DateTimeField(verbose_name='last_update_time')),
            ],
            options={
                'verbose_name': 'cp_platform_algorithm_flow',
                'verbose_name_plural': 'cp_platform_algorithm_flow',
                'db_table': 'cp_platform_algorithm_flow',
            },
        ),
        migrations.CreateModel(
            name='PlatformStreamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('stream_code', models.CharField(max_length=50, verbose_name='stream_code')),
                ('stream_nickname', models.CharField(max_length=100, verbose_name='stream_nickname')),
                ('node_codes', models.TextField(verbose_name='节点编号列表')),
                ('state', models.IntegerField(verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('last_update_time', models.DateTimeField(verbose_name='last_update_time')),
            ],
            options={
                'verbose_name': 'cp_platform_stream',
                'verbose_name_plural': 'cp_platform_stream',
                'db_table': 'cp_platform_stream',
            },
        ),
    ]
